name: demo_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  country_code_picker: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.2
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  timer_count_down: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
